-- MySQL Script generated by MySQL Workbench
-- Wed Jul  6 00:22:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `dt_both` DATETIME NOT NULL,
  `document` VARCHAR(14) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `device_token` VARCHAR(255) NULL,
  `city` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dt_created` DATETIME DEFAULT NOW(),
  `dt_updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_UNIQUE` (`document` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dt_created` DATETIME DEFAULT NOW(),
  `dt_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_users_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_users_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tb_users_id` INT NOT NULL,
  `tb_permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario_permissao_tb_users_idx` (`tb_users_id` ASC) ,
  INDEX `fk_tb_user_permission_tb_permission1_idx` (`tb_permission_id` ASC) ,
  CONSTRAINT `fk_tb_usuario_permissao_tb_users`
    FOREIGN KEY (`tb_users_id`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_permission_tb_permission1`
    FOREIGN KEY (`tb_permission_id`)
    REFERENCES `delivery`.`tb_permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_stores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `phone` VARCHAR(11) NULL,
  `description` VARCHAR(150) NULL,
  `image_url` VARCHAR(255) NULL,
  `latitude` VARCHAR(15) NOT NULL,
  `longitude` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `addresss_num` VARCHAR(6) NOT NULL,
  `address_complement` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `dt_created` DATETIME DEFAULT NOW(),
  `dt_updated` DATETIME NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) ,
  INDEX `fk_tb_store_tb_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_tb_store_tb_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(110) NULL,
  `dt_created` DATETIME DEFAULT NOW(),
  `dt_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `value` DOUBLE NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dt_created` DATETIME DEFAULT NOW(),
  `dt_updated` DATETIME NULL,
  `categories_id` INT NOT NULL,
  `stores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_products_tb_stores1_idx` (`stores_id` ASC) ,
  INDEX `fk_tb_products_tb_categories1_idx` (`categories_id` ASC) ,
  CONSTRAINT `fk_tb_products_tb_stores1`
    FOREIGN KEY (`stores_id`)
    REFERENCES `delivery`.`tb_stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_products_tb_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `delivery`.`tb_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_sells`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_sells` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(1) NOT NULL,
  `dt_created` DATETIME DEFAULT NOW(),
  `dt_updated` DATETIME NULL,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_sells_tb_products1_idx` (`products_id` ASC) ,
  INDEX `fk_tb_sells_tb_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_tb_sells_tb_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `delivery`.`tb_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_sells_tb_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_push` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `dt_created` DATETIME NULL,
  `tb_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_push_tb_users1_idx` (`tb_users_id` ASC) ,
  CONSTRAINT `fk_tb_push_tb_users1`
    FOREIGN KEY (`tb_users_id`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
